### ISSUE TITLE
Not able to run this container as daemon

### ISSUE THREAD

**Issue by SplunkVenkat** [ContinuumIO/docker-images#103]
every time i try running this image as deamon like "**docker run -d -p 80:8888 customanaconda** " it exits the container.

**Comment by ankit-jha** [comment]
Try running it as in
https://github.com/ContinuumIO/docker-images/issues/94

**Comment by dbast** [comment]
This can be e.g. done via:
```
docker run -d -p 8888:8888 continuumio/miniconda3 /bin/bash -c "\
        conda install jupyter -y --quiet && \
        mkdir -p /opt/notebooks && \
        jupyter notebook \
        --notebook-dir=/opt/notebooks --ip='*' --port=8888 \
        --no-browser --allow-root"
```

Thus closing. Please reopen, if this still is an issue.
