### ISSUE TITLE
ResolvePackageNotFound Error

### ISSUE THREAD

**Issue by wqp89324** [ContinuumIO/docker-images#109]
I'm trying to setup Anaconda and Docker with the following Dockerfile:

```
FROM continuumio/anaconda3

COPY environment.yml /tmp/environment.yml
RUN conda env create -f /tmp/environment.yml
```
The yml file is also attached (made a txt file in order to upload here [environment.yml.txt](https://github.com/ContinuumIO/docker-images/files/2724509/environment.yml.txt)). Although I can create env locally with this yml file, doing the same within Docker gives me ResolvePackageNotFound error:
```
ResolvePackageNotFound:
  - mkl_fft==1.0.6=py36hdbbee80_0
  - pygments==2.2.0=py36hb010967_0
  - wincertstore==0.2=py36h7fe50ca_0
  - scipy==1.1.0=py36h4f6bf74_1
  - icc_rt==2019.0.0=h3e97881_0
  - mkl_random==1.0.1=py36h77b88f5_1
  - markupsafe==1.1.0=py36he774522_0
  - numpy==1.15.4=py36ha559c80_0
  - qt==5.9.7=vc14h73c81de_0
  - scikit-learn==0.20.1=py36hb854c30_0
  - wrapt==1.10.11=py36hfa6e2cd_2
  - openssl==1.1.1a=he774522_0
  - vc==14.1=h0510ff6_4
  - cffi==1.11.5=py36h74b6da3_1
  - lazy-object-proxy==1.3.1=py36hfa6e2cd_2
  - mistune==0.8.4=py36he774522_0
  - docutils==0.14=py36h6012d8f_0
  - vs2015_runtime==14.15.26706=h3a45250_0
  - pywin32==223=py36hfa6e2cd_1
  - pyqt==5.9.2=py36h6538335_2
  - psutil==5.4.8=py36he774522_0
  - jsonschema==2.6.0=py36h7636477_0
  - zlib==1.2.11=h62dcd97_3
  - wcwidth==0.1.7=py36h3d5aa90_0
  - sip==4.19.8=py36h6538335_0
  - win_inet_pton==1.0.1=py36_1
  - jpeg==9b=hb83a4c4_2
  - libpng==1.6.35=h2a8f88b_0
  - pandas==0.23.4=py36h830ac7b_0
  - cryptography==2.4.1=py36h7a1dbc1_1
  - zeromq==4.2.5=he025d50_1
  - ipython_genutils==0.2.0=py36h3c5d0ee_0
  - typed-ast==1.1.0=py36hfa6e2cd_0
  - pyzmq==17.1.2=py36hfa6e2cd_0
  - python==3.6.7=h9f7ef89_2
  - libsodium==1.0.16=h9d3ae62_0
  - icu==58.2=ha66f8fd_1
  - tornado==5.1.1=py36hfa6e2cd_0
  - numpy-base==1.15.4=py36h8128ebf_0
  - traitlets==4.3.2=py36h096827d_0
  - snowballstemmer==1.2.1=py36h763602f_0
  - python-crfsuite==0.9.6=py36h6538335_0
  - nbformat==4.4.0=py36h3a5bc1b_0
  - sqlite==3.25.3=he774522_0

The command '/bin/sh -c conda env create -f /tmp/environment.yml' returned a non-zero code: 1
```

Can anyone please help?

**Comment by soapy1** [comment]
It looks like you just exported your environment from a windows machine and you are pinning to the build numbers. Since the docker container is not running windows this will fail. I would use an environment.yaml that has less specific pinning and only the packages that you actually want. Maybe something like:
```
name: envfortagk
channels:
  - defaults
dependencies:
  - alabaster=0.7.12
  - asn1crypto=0.24.0
  - astroid=2.1.0
  - babel=2.6.0
  - backcall=0.1.0
  - blas=1.0=mkl
  - bleach=3.0.2
...
```

**Comment by wqp89324** [comment]
@soapy1 Thanks a lot for your reply! Now I get it. However, after removing all these "pinning", I get a lot fewer issues, but still:
```
ResolvePackageNotFound:
  - icc_rt==2019.0.0=h3e97881_0
  - pywin32=223
  - win_inet_pton=1.0.1
  - wincertstore=0.2
  - vs2015_runtime=14.15.26706
  - vc=14.1
```
I guess Conda virtralenv is still not portable from Windows to Linux, as discussed in this thread?
[https://stackoverflow.com/questions/39105596/conda-python-virtual-environment-is-not-portable-from-windows-to-linux](url)

**Comment by soapy1** [comment]
Ya, those packages aren't available on Linux, I would remove them from your environment.yaml. `conda env export` will just dump all the packages you have for you. So I guess in a sense it is not portable. At the same time, I think that makes sense for what the command it meant to do, that is, export the current environment that you have.
Also, you can tell conda to not include the build string in an environment export by using the `--no-builds` flag

**Comment by wqp89324** [comment]
@soapy1 Thank you so much, this is already very helpful. I wish when conda exports yml, it can be aware of the targeted os, because yml is really to help people share their working virtual env, therefore conda should take into account the targeted os?
