### ISSUE TITLE
Can I run a docker image from inside a conda environment?

### ISSUE THREAD

**Issue by ajhool** [ContinuumIO/docker-images#110]
I hope it is not too obvious, but I'm not very experienced with either Docker or Conda.

I'm using an AWS AMI that comes prepackaged with an assortment of Deep Learning software libs and Conda environments. I can ssh into my instance and run `source activate pytorch_p36` and then execute my script using `python my-script.py`. Conda is great!

However, I'd like to use AWS Batch, which is a managed batch computing environment that uses a docker file as an entry point to execute my python script. If I run my Docker container inside a command prompt after running `source activate pytorch_p36` (or perhaps that executes in .bashrc), will the docker container see the environment that conda configured?

**Comment by soapy1** [comment]
The short answer I think you are looking for is: yes, you can run docker from inside a conda environment. But no, the environment will not be available to you from inside the docker container.

If you activate a conda environment you will still be able to run a docker container. For example
```
$ conda activate pytorch_p36
$ docker run -it fun/container do-a-thing
```
is an ok thing to do.

However, this does not mean that your activated environment is available in the docker container. One of the advantages of docker is the ability to run processes in isolation. 

If you want your conda environment available in the docker container, then you need to have conda installed in that container and then have that environment installed in that container.

**Comment by mingwandroid** [comment]
For testing on multiple linux 'distros' easily (I quoted distros because docker is only an approximation of actually using a given distro), I have various shell scripts called e.g. cos6.sh, ubuntu1810.sh, clear.sh, archlinux.sh .. and the exact same Miniconda installations are shared between them (I never run two at the same time though).

The line (for clear linux) is:

```
docker run -it \
    -v /opt/conda-linux-64:/opt/conda \
    -v /opt/conda-linux-32:/opt/conda-32 \
    -v ${HOME}:/root -it \
    clearlinux:latest /bin/bash
```

This works very well for my purposes (I host docker on macOS).
