### ISSUE TITLE
Error when running miniconda3 as per current documentation

### ISSUE THREAD

**Issue by santosomar** [ContinuumIO/docker-images#113]
I am running the container as per the example in Docker Hub and here and I am getting the following error:

```
[I 20:13:39.828 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
[C 20:13:40.069 NotebookApp] Running as root is not recommended. Use --allow-root to bypass.
```
Of course, you can use `--allow-root to bypass`. However, this is not secure.

**Comment by santosomar** [comment]
Forgot to add the syntax that I am using (which is the same as the documentation):

```
docker run -i -t  -p $8888:8888 continuumio/miniconda3:latest /bin/bash -c "/opt/conda/bin/conda install jupyter -y --quiet && mkdir /opt/notebooks && /opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip='0.0.0.0' --port=8888 --no-browser"
```

**Comment by jdblischak** [comment]
@santosomar I was able to run Jupyter by setting `--ip='0.0.0.0'` and `--allow-root`. See https://github.com/ContinuumIO/docker-images/issues/85#issuecomment-437152550

> Of course, you can use `--allow-root to bypass`. However, this is not secure.

The only user defined in the Docker image is the root user. If you want a non-root user, you'll need to create your own Docker image that builds on this one. Another workaround is described in https://github.com/ContinuumIO/docker-images/pull/65#issuecomment-334719303
