### ISSUE TITLE
python not found

### ISSUE THREAD

**Issue by mentgmery** [ContinuumIO/docker-images#119]
when I did  docker pull continuumio/anaconda,

it failed with the message below,

=====================
$ python --version
/bin/sh: eval: line 57: python: not found
ERROR: Job failed: exit code 127
=====================

**Comment by mentgmery** [comment]
confirmed it is a bug, when I add "image: continuumio/anaconda:2018.12" into ".gitlab.yml" file, it works.

**Comment by soapy1** [comment]
Could you provide more specifics for how you are getting this error?

For example, I pulled the newest anaconda
```
$ docker pull continuumio/anaconda
Using default tag: latest
latest: Pulling from continuumio/anaconda
8e402f1a9c57: Already exists
cfb65e3e7e95: Already exists
68ff28bc7a5b: Already exists
Digest: sha256:4f64f38b10cece2d431f6ff0c155b7025ab3adf4cf2434d1de7bf9d6170e7b3c
Status: Downloaded newer image for continuumio/anaconda:latest
```

I started an interactive shell
```
$ docker run -it  continuumio/anaconda:latest
```

verified that I had the anaconda version I expected 
```
(base) e6e84dd1eecd:/$ conda list | grep anaconda
WARNING: The conda.compat module is deprecated and will be removed in a future release.
anaconda                  2019.03                  py27_0
anaconda-client           1.7.2                    py27_0
anaconda-navigator        1.9.7                    py27_0
anaconda-project          0.8.2                    py27_0
```

check if python is available
```
(base) e6e84dd1eecd:/$ python --version
Python 2.7.16 :: Anaconda, Inc.
```

it exists. what are the steps you followed to get your error?

**Comment by leycec** [comment]
@mentgmery: While it *is* a bug, **it's a bug with GitLab-CI.** Numerous GitLab-CI users – including yourself, [us](https://gitlab.com/betse/betse/-/jobs/193817553), and @jennirinker – have faceplanted into the same issue over the past two days. Reverting to a prior version of the `continuumio/anaconda` Dockerfile is a stopgap solution at best.

See [this discussion](https://github.com/ContinuumIO/docker-images/issues/122#issuecomment-481548585) for further details. In particular, it'd be awesome if you wouldn't mind submitting a [new GitLab-CI issue](https://gitlab.com/gitlab-org/gitlab-runner/issues) on this topic *or* commenting in this [existing related GitLab-CI issue](https://gitlab.com/gitlab-org/gitlab-runner/issues/4125). Ideally, someone sensible at GitLab will escalate this and rapidly kick out a new GitLab point release patching this up. `</sigh>`

**Comment by leycec** [comment]
@soapy1: **Wait.** This *might* be an Anaconda-side issue after all. See [#122](https://github.com/ContinuumIO/docker-images/issues/122#issuecomment-481588288) for further discussion. *Urgh.* :face_with_head_bandage:
