### ISSUE TITLE
Anaconda3 Docker image missing bash

### ISSUE THREAD

**Issue by slipperysaxophone** [ContinuumIO/docker-images#120]
Image: 9e186aada2ee

Following the readme:
`docker run -i -t continuumio/anaconda3 /bin/bash
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown.
`

Only available shell is 'sh'. The following will work:
`docker run -i -t continuumio/anaconda3 /bin/sh`

**Comment by soapy1** [comment]
We have changed from using debian as the base image to alpine in order to make our images leaner and more efficient. Alpine doesn't support bash, so this is what you are running into. IMHO using `/bin/sh` should be sufficient, but is there anything you are terribly stuck on that bash is a must have?

**Comment by alexiswl** [comment]
You may wish to extend the docker file and install bash into it, see the reference below.
https://www.cyberciti.biz/faq/alpine-linux-install-bash-using-apk-command/

I needed to do this in order to install etetoolkit through conda.

as a docker example:
```
FROM: continuumio/anaconda3:2019.03

RUN apk update
RUN apk upgrade
RUN apk add bash
```

or a singularity example
```
BootStrap: docker
From: continuumio/anaconda3:2019.03

%post
# Update alpine
apk update
apk upgrade
apk add bash
```

**Comment by pierre-nicolas-nelio** [comment]
We could not manage to install anything with `apk` because the user was redefined as `anaconda`, which has (as far as I understand) no sudo permissions.

This broke our prod pipeline, BTW.

**Comment by mikedh** [comment]
Hey, switching the `latest` tag to Alpine does have the unfortunate effect of breaking any downstream things using anything *other* than straight Python or conda. I noticed it when `apt-get` no longer existed, in the OP's instance `bash`. The way Python itself does this is [through tags](https://hub.docker.com/_/python/?tab=tags) which is kind of nice, which could look in this case like:

`continuumio:anaconda3:alpine`
`continuumio:anaconda3:latest`

**Comment by soapy1** [comment]
@mikedh we don't really intend on continuing to build docker images using debian:latest. This pr https://github.com/ContinuumIO/docker-images/pull/117 updated our dockerfiles changed our base image to alpine and also made a lot of nice improvements to make the images safer and smaller. 

That being said, if community members have such strong conviction that they really need a debian/jessie/whatever based docker image then we are accepting PRs. And then we will also be happy to inherit the job of building those images and making them available on docker hub, probably using a similar scheme to what python is doing with their images.

**Comment by jennirinker** [comment]
Hi @soapy1 , it does seem that this change breaks any CI pipelines using the anaconda image if there are any packages to be installed using pip (including the main package). 

I was using the anaconda images pretty much exclusively for my CI pipelines, so to suddenly have them all broken is a bit rough. Any chance that pip at least could be usable in the image?

**Comment by soapy1** [comment]
pip is usable in the image is gets installed with python

eg.
```
$ docker run -it  continuumio/anaconda3:latest
(base) 84d2a43b07e9:/$ pip install ansible
Collecting ansible
  Downloading https://files.pythonhosted.org/packages/9a/9d/5e3d67bd998236f32a72f255394eccd1e22b3e2843aa60dc30dd164816d0/ansible-2.7.10.tar.gz (11.8MB)
    100% |████████████████████████████████| 11.8MB 3.7MB/s
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.7/site-packages (from ansible) (2.10)
Requirement already satisfied: PyYAML in /opt/conda/lib/python3.7/site-packages (from ansible) (5.1)
Collecting paramiko (from ansible)
  Downloading https://files.pythonhosted.org/packages/cf/ae/94e70d49044ccc234bfdba20114fa947d7ba6eb68a2e452d89b920e62227/paramiko-2.4.2-py2.py3-none-any.whl (193kB)
    100% |████████████████████████████████| 194kB 3.4MB/s
Requirement already satisfied: cryptography in /opt/conda/lib/python3.7/site-packages (from ansible) (2.6.1)
Requirement already satisfied: setuptools in /opt/conda/lib/python3.7/site-packages (from ansible) (40.8.0)
Requirement already satisfied: MarkupSafe>=0.23 in /opt/conda/lib/python3.7/site-packages (from jinja2->ansible) (1.1.1)
Collecting bcrypt>=3.1.3 (from paramiko->ansible)
  Downloading https://files.pythonhosted.org/packages/d0/79/79a4d167a31cc206117d9b396926615fa9c1fdbd52017bcced80937ac501/bcrypt-3.1.6-cp34-abi3-manylinux1_x86_64.whl (55kB)
    100% |████████████████████████████████| 61kB 10.1MB/s
Collecting pynacl>=1.0.1 (from paramiko->ansible)
  Downloading https://files.pythonhosted.org/packages/27/15/2cd0a203f318c2240b42cd9dd13c931ddd61067809fee3479f44f086103e/PyNaCl-1.3.0-cp34-abi3-manylinux1_x86_64.whl (759kB)
    100% |████████████████████████████████| 768kB 2.5MB/s
Collecting pyasn1>=0.1.7 (from paramiko->ansible)
  Downloading https://files.pythonhosted.org/packages/7b/7c/c9386b82a25115cccf1903441bba3cbadcfae7b678a20167347fa8ded34c/pyasn1-0.4.5-py2.py3-none-any.whl (73kB)
    100% |████████████████████████████████| 81kB 5.0MB/s
Requirement already satisfied: asn1crypto>=0.21.0 in /opt/conda/lib/python3.7/site-packages (from cryptography->ansible) (0.24.0)
Requirement already satisfied: six>=1.4.1 in /opt/conda/lib/python3.7/site-packages (from cryptography->ansible) (1.12.0)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in /opt/conda/lib/python3.7/site-packages (from cryptography->ansible) (1.12.2)
Requirement already satisfied: pycparser in /opt/conda/lib/python3.7/site-packages (from cffi!=1.11.3,>=1.8->cryptography->ansible) (2.19)
Building wheels for collected packages: ansible
  Building wheel for ansible (setup.py) ... done
  Stored in directory: /home/anaconda/.cache/pip/wheels/b1/87/37/8f982acaa4fd348505aa36789e2273ee362dbce98716d14cba
Successfully built ansible
Installing collected packages: bcrypt, pynacl, pyasn1, paramiko, ansible
Successfully installed ansible-2.7.10 bcrypt-3.1.6 paramiko-2.4.2 pyasn1-0.4.5 pynacl-1.3.0
```

**Comment by jennirinker** [comment]
Yep, I didn't understand what was going on with the GitLab entry point -- the issue is GitLab and not the docker image. Sorry about my confusion.

**Comment by leycec** [comment]
@soapy1 The *Usage* subsection of the [official `continuumio/anaconda3` documentation](https://hub.docker.com/r/continuumio/anaconda3) erroneously references `bash` in multiple commands – notably:

> You can download and run this image using the following commands:

```
docker pull continuumio/anaconda3
docker run -i -t continuumio/anaconda3 /bin/bash
```

> Alternatively, you can start a Jupyter Notebook server and interact with Anaconda via your browser:

    docker run -i -t -p 8888:8888 continuumio/anaconda3 /bin/bash -c "/opt/conda/bin/conda install jupyter -y --quiet && mkdir /opt/notebooks && /opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip='*' --port=8888 --no-browser"

Unrelatedly, it's unfortunate that swapping Debian for Alpine so fundamentally ruptured backwards compatibility with existing CI configurations. In hindsight, it might have been preferable to deprecate the existing Debian-based `continuumio/anaconda3` Dockerfile and then define a new Alpine-based Dockerfile under a unique name (e.g., `continuumio/anaconda3-alpine`).

In any case, thanks for all the continued analytics! Calculon *mostly* approves. :robot:

**Comment by pierre-nicolas-nelio** [comment]
@soapy1 
> If you really need bash in the docker image for some reason, I would suggest building an image with anaconda as your base image.

You indeed need bash to run one of the most basic `anaconda` commands : `source activate myenv`.

Maybe it could be useful to add bash to the Docker after all?

**Comment by soapy1** [comment]
@pierre-nicolas-nelio so I tried to replicate your issue with activating environments, here is what I found:

```
$ docker run -it continuumio/anaconda3:latest
(base) c258639317de:/$ conda create -n testenv zope
WARNING: The conda.compat module is deprecated and will be removed in a future release.
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /opt/conda/envs/testenv

  added / updated specs:
    - zope


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    zope-1.0                   |           py37_1           4 KB
    ------------------------------------------------------------
                                           Total:           4 KB

The following NEW packages will be INSTALLED:

  ca-certificates    pkgs/main/linux-64::ca-certificates-2019.1.23-0
  certifi            pkgs/main/linux-64::certifi-2019.3.9-py37_0
  libedit            pkgs/main/linux-64::libedit-3.1.20181209-hc058e9b_0
  libffi             pkgs/main/linux-64::libffi-3.2.1-hd88cf55_4
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-8.2.0-hdf63c60_1
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-8.2.0-hdf63c60_1
  ncurses            pkgs/main/linux-64::ncurses-6.1-he6710b0_1
  openssl            pkgs/main/linux-64::openssl-1.1.1b-h7b6447c_1
  pip                pkgs/main/linux-64::pip-19.0.3-py37_0
  python             pkgs/main/linux-64::python-3.7.3-h0371630_0
  readline           pkgs/main/linux-64::readline-7.0-h7b6447c_5
  setuptools         pkgs/main/linux-64::setuptools-40.8.0-py37_0
  sqlite             pkgs/main/linux-64::sqlite-3.27.2-h7b6447c_0
  tk                 pkgs/main/linux-64::tk-8.6.8-hbc83047_0
  wheel              pkgs/main/linux-64::wheel-0.33.1-py37_0
  xz                 pkgs/main/linux-64::xz-5.2.4-h14c3975_4
  zlib               pkgs/main/linux-64::zlib-1.2.11-h7b6447c_3
  zope               pkgs/main/linux-64::zope-1.0-py37_1


Proceed ([y]/n)? y


Downloading and Extracting Packages
zope-1.0             | 4 KB      | ################################################################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate testenv
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) c258639317de:/$ source activate testenv
(testenv) c258639317de:/$ conda deactivate
(base) c258639317de:/$ conda activate testenv
(testenv) c258639317de:/$ conda deactivate
(base) c258639317de:/$
```

so activating environments is fine. 

However, I did a little more digging and I did find an instance where not having bash broke stuff.

```
(base) c258639317de:/$ conda install paramiko
WARNING: The conda.compat module is deprecated and will be removed in a future release.
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /opt/conda

  added / updated specs:
    - paramiko

  ........

Verifying transaction: done
Executing transaction: failed
ERROR conda.core.link:_execute(568): An error occurred while installing package 'defaults::pyasn1-0.4.5-py_0'.
FileNotFoundError(2, "No such file or directory: 'bash'")
Attempting to roll back.

Rolling back transaction: done

[Errno 2] No such file or directory: 'bash': 'bash'
```

looking into it

**Comment by soerface** [comment]
Have you considered using debian stretch-slim as a base image? I've even achieved smaller images with it compared to alpine in some cases.

Changing to alpine without any warning is a major compatibility break, and gives me serious doubts as to using your images in a production CI pipeline is a good idea.

**Comment by bryevdv** [comment]
@soapy1 It would seem just installing pyparsing is also no longer possible:

```
Step 10/17 : RUN conda install --yes --quiet python=${PY_VERSION} pyyaml jinja2 bokeh=${BK_VERSION} numpy numba scipy sympy nodejs>=8.8 pandas scikit-learn
 ---> Running in 09de32d5f69b
ERROR conda.core.link:_execute(568): An error occurred while installing package 'defaults::pyparsing-2.4.0-py_0'.
FileNotFoundError(2, "No such file or directory: 'bash'")
Attempting to roll back.


[Errno 2] No such file or directory: 'bash': 'bash'

The command '/bin/sh -c conda install --yes --quiet python=${PY_VERSION} pyyaml jinja2 bokeh=${BK_VERSION} numpy numba scipy sympy nodejs>=8.8 pandas scikit-learn' returned a non-zero code: 1
```

**Comment by fritz-clicktripz** [comment]
The Click package, installed often as a sub-dependency, is also broken
```
ERROR conda.core.link:_execute(568): An error occurred while installing package 'conda-forge::click-7.0-py_0'.
FileNotFoundError(2, "No such file or directory: 'bash'")
```

**Comment by xhochy** [comment]
Also conda-build has `/bin/bash` hardcoded https://github.com/conda/conda-build/blob/403498b3c659cb8abfe01ece142364c13b731b3f/conda_build/build.py#L88 which makes it unusable in the miniconda image.
