### ISSUE TITLE
Switch from debian to alpine not reflected in dockerhub Dockerfile

### ISSUE THREAD

**Issue by psathyrella** [ContinuumIO/docker-images#123]
I can't really comment on the merits of the switch, and there's plenty of discussion in other issues, but the current [Dockerfile in dockerhub](https://hub.docker.com/r/continuumio/anaconda/dockerfile) seems to still say it's pulling `debian:latest`. It would've saved quite some time in tracking down the source of things broken by the switch to Alpine if the dockerfile reflected that switch.

thanks

edit: for additional context, if I pull continuumio/anaconda from dockerhub, I still get debian. I don't know much about how the infrastructure works, but presumably this is because the images that dockerhub's autmoated build uses (that have alpine) are built by you folks, whereas when I pull from dockerhub it's still using the actual dockerfile on docker hub, which uses debian.

**Comment by alexiswl** [comment]
The tags in dockerhub for anaconda were recently switched (see commit fae5a1de)
2019.03 tag was moved from alpine to debian base.
2019.03-alpine tag is now the docker tag for the alpine base.

In my understanding of DockerHub, the 'latest' tag can be moved to point to particular tags manually. So 'latest' may not be the most recent build. I think what's shown on the 'Dockerfile' is different through

From the comments in the header of the dockerfile shown at DockerHub.com it looks like this DockerFile shown is linked to the commit hash 'af10934'.
This may be a bug in DockerHub though, looking at the 'builds' it appears that all of them are over one year ago, which is incorrect.

**Comment by soapy1** [comment]
@alexiswl, yup!
We have stoped doing builds on docker hub and currently have a ticket to sort out removing that dockerfile. @psathyrella sorry for the confusion this has caused

**Comment by roccqqck** [comment]
may i ask 
which tag or which dockerfile is the lastest  stable version?

**Comment by dbast** [comment]
This got resolved by what alexiswl wrote and the python 2.7 based anaconda image is anyway not built anymore. Thus closing.
