### ISSUE TITLE
"conda clean --source-cache deprecated" warning on build

### ISSUE THREAD

**Issue by majidaldo** [ContinuumIO/docker-images#129]
https://github.com/ContinuumIO/docker-images/blob/dd43b728c848baacd718b185b29148e57b48dee2/miniconda3/debian/Dockerfile#L19

on building
```
WARNING: 'conda clean --source-cache' is deprecated.
    Use 'conda build purge-all' to remove source cache files.
```

(but conda build isn't installed)

**Comment by dbast** [comment]
This got fixed by https://github.com/ContinuumIO/docker-images/commit/4ed8fdac4647e4cc4210f84a327c3b7c92802b5d
