### ISSUE TITLE
pip not available on continuumio/anaconda3:2019.07

### ISSUE THREAD

**Issue by Guillermogsjc** [ContinuumIO/docker-images#138]
Hi, there is an error when calling `pip/pip3` on this image. Is this an expected behaviour?

`/bin/sh: 1: pip3: not found`
 
On `2019.03` version everything is fine with `pip/pip3`.

Thanks!

**Comment by Quantmatic** [comment]
conda install -c anaconda pip

or

conda create -n myenv  python=3.6 pip

**Comment by soapy1** [comment]
how are you calling docker? For example, running `docker run -it continuumio/anaconda3:2019.07` or `docker run -it continuumio/anaconda3:2019.07 bash` the conda environment will be active. Running `docker run -it continuumio/anaconda3:2019.07 sh` will not give you an active conda environment (in this case you are overriding the default entry point) however, you can activate conda by running `. /opt/conda/bin/activate` and then pip (and conda) will be on path

**Comment by Guillermogsjc** [comment]
Hi,

On 2019.03 this usual Dockerfile standard line after image load works, on
2019.07 does not:

`RUN pip install -r requirements`

Anyway thanks for the workaround, from 2019.07, before pip one must install
it from conda before as Alek proposes, or activate the environment before
as Sophia suggests.

Thanks both.

**Comment by mingwandroid** [comment]
Closing. Activation is the only supported use case here.
