### ISSUE TITLE
continuumio/miniconda3:4.7.10 broken in GitLab runner?

### ISSUE THREAD

**Issue by andrew-schweitzer-analog** [ContinuumIO/docker-images#144]
Our GitLab CI scripts pulling `continuumio/miniconda3:latest` or (`continuumio/miniconda3:4.7.10`) stopped working in the last few hours. They report that conda is not in the path. 

If I pull the image and run it locally, with: 
```
docker pull continuumio/miniconda3
docker run -i -t continuumio/miniconda3 /bin/bash
``` 
conda _is_ in the path. The image `continuumio/miniconda3:4.6.14` also has conda in the path.  

Should we be adding conda to the path with the 4.7 image? 

Thanks,

Andy

**Comment by andrew-schweitzer-analog** [comment]
This diff seems to show the entry point being removed from the image: https://github.com/ContinuumIO/docker-images/commit/cac3352bf21a26fa0b97925b578fb24a0fe8c383#diff-f457937faa53d4e944124728c5999a51, apparently to save space.

**Comment by forrestwaters** [comment]
You'll need to activate conda before using it. You can try this (which is in the `.bashrc` file for root in the new images):
``` 
. /opt/conda/etc/profile.d/conda.sh && \
 conda activate base
```

**Comment by andrew-schweitzer-analog** [comment]
Thanks. That worked. 

Insofar as others use GitLab CI with this image, it might be worth documenting this, perhaps on overview page for the image. I'm personally all set, so feel free to close this if you don't plan doc updates or other modifications.
