### ISSUE TITLE
conda and activate not found in $PATH?

### ISSUE THREAD

**Issue by samarths-msft** [ContinuumIO/docker-images#145]
Hi,

I have a Dockerfile which looks something like this:

FROM continuumio/miniconda3
…

RUN [ "conda", "env", "create", "-f", "/code/myenv.yml" ]

ENTRYPOINT [ "/bin/bash", "-c", "source activate myenv && cd /code && exec python mycode.py $0" ]

This was working fine until recently, but now I started seeing "exec: "conda": executable file not found in $PATH"

So I updated "conda" in the RUN statement to /opt/conda/bin/conda and that error went away.

But now I'm seeing "/bin/bash: activate: No such file or directory"

Probably this is also related to the fact that my $PATH didn't contain the path to activate.

How/why did this work (for nearly a year) earlier? What's the recommended fix here?

Incidentally, I'm also seeing the following:

----
==> WARNING: A newer version of conda exists. <==
  current version: 4.7.10
  latest version: 4.7.11

Please update conda by running

    $ conda update -n base -c defaults conda
----

Any idea when the continuumio/miniconda3 base image will automatically contain the latest version of conda?

Thanks!

**Comment by jcorb** [comment]
I have hit this same issue.  My guess is that it is somehow related to this commit [https://github.com/ContinuumIO/docker-images/pull/142/commits/e31d7327daff335eba12706d1f42235f5e3b0424](url) but its not obvious (to me at least) why 🤷‍♂.

A fix is to pin the Docker image version, e.g.
change `FROM continuumio/miniconda3` to `FROM continuumio/miniconda3:4.6.14`

**Comment by simoneggler** [comment]
i have the same problem

**Comment by jan-janssen** [comment]
According to https://github.com/ContinuumIO/docker-images/pull/141#issuecomment-522286881 it is a feature not a bug.

**Comment by forrestwaters** [comment]
Sorry about this - please see the update here: https://github.com/ContinuumIO/docker-images/issues/147#issuecomment-524050218
