### ISSUE TITLE
Conda command no longer available in lastest docker image

### ISSUE THREAD

**Issue by likewei92** [ContinuumIO/docker-images#146]
`docker run continuumio/miniconda3 which conda` returns blank

**Comment by uijl** [comment]
This is a duplicate from #145, the answer provided works (as a temporary solution).

**Comment by forrestwaters** [comment]
We just built a new miniconda image which puts conda back on PATH. Sorry for the breakage. Please let us know if this fixes your problems

**Comment by likewei92** [comment]
Yep it works now. Thanks!
