### ISSUE TITLE
pip and curl not found on the miniconda:latest image

### ISSUE THREAD

**Issue by sroet** [ContinuumIO/docker-images#147]
I am using the `miniconda:latest` image for my CI and since this morning all my jobs start failing with either:
`/bin/bash: line 68: curl: command not found`
or
`/bin/bash: line 89: pip: command not found`

**Comment by jan-janssen** [comment]
This is a duplicate from https://github.com/ContinuumIO/docker-images/issues/145, the answer provided works (as a temporary solution).

**Comment by dparkar** [comment]
Same here. Builds are running on Azure DevOps using the built-in Docker task. Pinned version to 4.6.14 for now.

**Comment by forrestwaters** [comment]
We just built a new miniconda image which puts conda back on PATH. Sorry for the breakage. Please let us know if this fixes your problems.

**Comment by sroet** [comment]
Curl is still not installed, but I can understand this was done to slim down the docker image and I add that to the CI script. Other than that it seems to work.
