### ISSUE TITLE
Add latest-alpine tags

### ISSUE THREAD

**Issue by OrangeDog** [ContinuumIO/docker-images#158]
There are currently versioned alpine tags for the images, but no latest.

**Comment by dbast** [comment]
Won't be done as latest points to the Debian image. A `latest-alpine` is not possible as tag prefixes are only added to tags not to latest by the current docker-meta action used to derive the tags https://github.com/ContinuumIO/docker-images/blob/master/.github/workflows/miniconda_alpine_ci.yml#L43
