### ISSUE TITLE
miniconda{2,3}:4.7.12-alpine conda not found

### ISSUE THREAD

**Issue by maciejmotyka** [ContinuumIO/docker-images#164]
This simple Dockerfile runs ok with miniconda2:4.7.12 non-alpine container, but fails with both miniconda2:4.7.12-alpine and miniconda3:4.7.12-alpine.
```
FROM continuumio/miniconda3:4.7.12-alpine

RUN conda install -c bioconda -c conda-forge savage=0.4.1
```
```
Step 2/2 : RUN conda install -c bioconda -c conda-forge savage=0.4.1
 ---> Running in 48489774abcc
/bin/sh: conda: not found
```
If the cause is the same as in #134, then I fail to comprehend why this is a desired behaviour.

**Comment by wbadart** [comment]
Any movement on this? `/opt/conda/bin` is still missing from the PATH on 4.8.2.

**Comment by pbarker** [comment]
This is still a thing?

**Comment by dbast** [comment]
Thanks for reporting. This got fixed a while ago and works e.g. with the current alpine image: `docker run -it continuumio/miniconda3:4.10.3-alpine conda install -c bioconda -c conda-forge savage=0.4.1`. Thus closing.

**Comment by wbadart** [comment]
Awesome, thanks!
