### ISSUE TITLE
Installing Java in continuumio/miniconda3 fails

### ISSUE THREAD

**Issue by tcasstevens** [ContinuumIO/docker-images#165]
Dear ContinuumIO,

We are using continuumio/miniconda3 as the base for our Dockerfile.  Mostly it is working well, thank you.  But when I try to install Java it fails.  Do you know how I can resolve this?

Thank you,

Terry

commands used...
apt-get update
apt-get install default-jdk

Error message...
Processing triggers for mime-support (3.62) ...
Processing triggers for libglib2.0-0:amd64 (2.58.3-2+deb10u1) ...
Processing triggers for libc-bin (2.28-10) ...
Setting up glib-networking:amd64 (2.58.0-2) ...
Setting up libsoup2.4-1:amd64 (2.64.2-2) ...
Setting up libsoup-gnome2.4-1:amd64 (2.64.2-2) ...
Setting up librest-0.7-0:amd64 (0.8.1-1) ...
Setting up libgtk-3-0:amd64 (3.24.5-1) ...
Setting up libgtk-3-bin (3.24.5-1) ...
Setting up libatk-wrapper-java-jni:amd64 (0.33.3-22) ...
Processing triggers for libgdk-pixbuf2.0-0:amd64 (2.38.1+dfsg-1) ...
Processing triggers for libc-bin (2.28-10) ...
Errors were encountered while processing:
 openjdk-11-jre-headless:amd64
 openjdk-11-jre:amd64
 openjdk-11-jdk-headless:amd64
 default-jre
 default-jdk-headless
 openjdk-11-jdk:amd64
 default-jdk
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by dbast** [comment]
This is an issue of the underlying debian base image, see e.g. https://github.com/debuerreotype/docker-debian-artifacts/issues/24#issuecomment-360870939

So the solution is to run `mkdir -p /usr/share/man/man1` before running the mentioned apt-get commands.
