### ISSUE TITLE
Publish new debian slim images on hub.docker.com

### ISSUE THREAD

**Issue by dkapitan** [ContinuumIO/docker-images#169]
I was wondering when the new debian-slim Docker images are planned for release on hub.docker.com?

I am am currently working to update bokeh/ docker-tools and would like to use the new slim base image. See https://github.com/bokeh/bokeh/issues/9581

Happy to just copy the Dockerfile to the Bokeh repository, but thought it would be more user friendly to start with an official image.

**Comment by dbast** [comment]
New images based on debian:buster-slim have been published since then. Thus closing, please reopen, if this still is an issue.
