### ISSUE TITLE
Cannot run package manager on Alpine

### ISSUE THREAD

**Issue by andreacassioli** [ContinuumIO/docker-images#175]
I am trying to switch to an `alpine` version `miniconda3` and I need to install some packages using the alpine package manager `apk`. However, the image comes already with `anaconda` user that has no privileges to do that. 

What is the rationale? This approach makes harder to customise a `miniconda` image.`alpine` makes very easy to switch to a non root user once the setup is done.

**Comment by infowolfe** [comment]
```USER root
RUN apk update && apk upgrade && apk add foo
USER anaconda
```
