### ISSUE TITLE
Not able to install mysql-server in continuumio/miniconda3 docker container

### ISSUE THREAD

**Issue by mdrijwan123** [ContinuumIO/docker-images#176]
I am trying to install the MySQL-server on top of latest base of continuumio/miniconda3 image using a command:
`RUN apt-get install mysql-server`

But the build is failing and it's giving error:
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package mysql-server is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'mysql-server' has no installation candidate

I am not able to understand where I am doing wrong, I don't think that the MySQL already installed there as in interactive mode of the container I am able to see: `bash: mysql: command not found `

**Comment by dbast** [comment]
Debian switched to mariadb (a fork of mysql), see e.g. https://mariadb.com/kb/en/moving-from-mysql-to-mariadb-in-debian-9/ 

So `apt-get install mariadb-server` is the solution.
