### ISSUE TITLE
Please add continuumio/miniconda3:4.8.4 to Docker hub

### ISSUE THREAD

**Issue by bsolomon1124** [ContinuumIO/docker-images#179]
The latest miniconda3 image on Docker hub as of now looks to be 4.8.2.  It looks like 4.8.4 contains [more than a handful of bugfixes](https://docs.conda.io/projects/conda/en/latest/release-notes.html) so making it available on Docker hub would be much appreciated.

**Comment by dbast** [comment]
4.8.3, 4.9.2 and 4.10.3 have been made available since then (see https://hub.docker.com/r/continuumio/miniconda3/tags?page=1&ordering=last_updated), thus closing.
