### ISSUE TITLE
No Miniconda 4.8.3 releases on docker hub

### ISSUE THREAD

**Issue by forana** [ContinuumIO/docker-images#183]
Related to #179 - https://repo.anaconda.com/miniconda/ has had `4.8.3` available for some time, but `4.8.2` is still the latest on docker hub.

**Comment by forana** [comment]
Worth noting that conda `4.9.0` is now available - every image built off of this gets a warning about it.

**Comment by forana** [comment]
Closing - looks like this happened at some point.

**Comment by marcindulak** [comment]
Just to confirm, is this the dockerhub repository https://hub.docker.com/r/continuumio/miniconda3?

**Comment by forana** [comment]
@marcindulak that's the one - `4.8.3` and `4.8.3-alpine` were pushed 3 months ago.
