### ISSUE TITLE
Add procps  the debian-based and bash to alpine-based Dockerfiles

### ISSUE THREAD

**Issue by alanhoyle** [ContinuumIO/docker-images#196]
A common use case for miniconda-based images is to run workflows on HPC.  Many workflow engines, like [Nextflow.io](https://nextflow.io), can report on CPU and RAM utilization by a subprocess if the `ps` command is included in the container and Nextflow-specifically won't work at all if bash isn't installed.  

The debian-based `Dockerfile`'s all lack the `procps` which would include `ps` and all of the alpine-based lack `bash`.  

In testing, adding `procps` to one of the debian-based images increases size by only 1-2 MB, and adding `apk add bash` adds about 4 MB to the alpine-based images.   

Including these would save an `apt-get update && apt-get install procps && apt-get clean` or `apk add bash` that would otherwise be required in every image built to run on Nextflow.  

If this is something that the maintainers would consider including in the base images, I will create a pull request to add these to the `Dockerfile`'s in the repo.  

It's worth noting that both debian and alpine images contain the [other requirements for Nextflow](https://www.nextflow.io/docs/latest/tracing.html#tasks): `awk`, `date`, `grep`, `egrep`, `sed`, `tail`, and `tee`.  It's just `bash` missing from alpine, and `ps` missing from debian.

**Comment by dbast** [comment]
ps got added as part of https://github.com/ContinuumIO/docker-images/pull/223
bash got added to alpine as part of https://github.com/ContinuumIO/docker-images/pull/232

Current latest and tagged miniconda3 releases already contain those updates. continuumio/anaconda3:latest contains ps, next release will also add bash to alpine.

**Comment by alanhoyle** [comment]
Late follow-up, but thanks @dbast for helping and closing this.
