### ISSUE TITLE
Make it VERY CLEAR that continuumio/miniconda is based on Python 2

### ISSUE THREAD

**Issue by MarcSkovMadsen** [ContinuumIO/docker-images#198]
Hi.

Thanks for providing these docker images.

My pain: I spent half a day trying to understand why I could not get the [HoloViz Panel developer guide](https://panel.holoviz.org/developer_guide/index.html) working inside a docker container.

It turns out I the problem was my base image `continuumio/miniconda` which is based on Python 2. I can see it's stated. But if possible **make it even clearer** by stating at the top in capitalized, bold letters.

My hypothesis is that less and less people would be aware of Python 2. They would assume things are Python 3. Personally I've been using Python for 4 years but never Python 2.

![image](https://user-images.githubusercontent.com/42288570/108617095-d9127c00-7413-11eb-973b-4c61ec491705.png)

**Comment by dbast** [comment]
The old Python 2 based anaconda/miniconda folders with README and Dockerfile got removed, due to Python 2 being EOL.

The description here https://hub.docker.com/r/continuumio/miniconda got updated to contain an extra note.
