### ISSUE TITLE
Create light example/sample of follow on Docker image

### ISSUE THREAD

**Issue by rgbkrk** [ContinuumIO/docker-images#2]
It would be nice to see what the best practice would be for a follow on image.

* If I know Docker, how do I get started using miniconda in this way?
* Where should my conda environments go if I create a new user?

**Comment by mutirri** [comment]
Basic `README.md` file was added to this repository.
Please follow the link from inside.

> Where should my conda environments go if I create a new user?

Docker uses `root` account per default.
The default installation path for `conda` is `/opt/conda`.
All necessary information you can obtain by performing:
```
$ conda info
```
If you create new user inside docker image then he will be able to use conda's environments in `read-only` mode (e.g. creating any new virtual environment requires `root` access) - unless you recursively change owner of `/opt/conda` directory, according to this new user.
For multi users `read-write` setup you can change perms on `/opt/conda` to `0777`.
Of course you can always install separate `anaconda/miniconda` environment for each of user as well.
