### ISSUE TITLE
Missing information for docker containers. What operating system is used?

### ISSUE THREAD

**Issue by soerendip** [ContinuumIO/docker-images#204]
I am wondering where to find information on what operating system these containers are using e.g.:

https://hub.docker.com/r/continuumio/miniconda 

It is stated Linux, but is it CentOS, Ubuntu? I am looking for an Ubuntu20.04 based container.

**Comment by csoja** [comment]
Please see https://github.com/ContinuumIO/docker-images

**Comment by soerendip** [comment]
Hm, not sure where to find the required information without digging in source codes. I was more looking for a short notice directly at the docker hub page. 'This container uses CentOS' or Ubuntu or whatever operating system was used.
