### ISSUE TITLE
Feature Request: docker image for anaconda for arm machines

### ISSUE THREAD

**Issue by Vineet-Sharma29** [ContinuumIO/docker-images#209]
I went through one of the recent announcement for anaconda support for AWS Graviton2. However, couldn't find any arm compatible docker image for anaconda and miniconda on dockerhub. 

I tried building an image by running the commands given [here](https://docs.anaconda.com/anaconda/install/graviton2/), it would throw error since installation requires interactive input which isn't possible in `docker build` command.

**Comment by dbast** [comment]
There are now various debian or amazonlinux based images for anaconda/miniconda on dockerhub:
* continuumio/anaconda3:latest (linux/arm64 Debian based)
* continuumio/anaconda3:2021.05-amazonlinux (linux/arm64 amazonlinux based)
* continuumio/miniconda3:4.10.3 (linux/arm64 Debian based)
