### ISSUE TITLE
Unable to verify the certificate

### ISSUE THREAD

**Issue by tboquet** [ContinuumIO/docker-images#22]
I used the base of the Dockerfile to build a container based on Ubuntu but I'm not able to download the script. When removing the `--quiet` option I get:

``` bash
ERROR: cannot verify repo.continuum.io's certificate, issued by '/C=US/O=thawte, Inc./CN=thawte SSL CA - G2':
  Unable to locally verify the issuer's authority.
To connect to repo.continuum.io insecurely, use `--no-check-certificate'.
The command '/bin/sh -c wget https://repo.continuum.io/miniconda/Miniconda2-3.19.0-Linux-x86_64.sh' returned a non-zero code: 5
```

I resolved it adding `--no-check-certificate`.

**Comment by bkreider** [comment]
I'm pretty sure that is a regression upstream in Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=812708.

**Comment by dbast** [comment]
This should be solved. Please reopen, if that issue still exists.
