### ISSUE TITLE
Please either remove entripoint entirely, or make it use -c option

### ISSUE THREAD

**Issue by wvxvw** [ContinuumIO/docker-images#222]
As of right now, the images named `docker.io/continuumio/conda-ci-linux-64-python*.*` are produced with:

``` dockerfile 
ENTRYPOINT [ "/bin/bash" ]
```

This is, basically, useless, as it overrides a better default, and prevents anyone from being able to do trivial things like:

``` sh
docker run -ti docker.io/continuumio/conda-ci-linux-64-python3.7 -- sh
```

---

While docker allows overriding entrypoint, for the life of me, I cannot figure out how to replace it with `/bin/bash -c` as it will think the entire string is the name of the executable...

**Comment by dbast** [comment]
The docker.io/continuumio/conda-ci-linux-64-python*.* images are intended to be use by the CI of https://github.com/conda/conda ... please use the miniconda3 (or anaconda3 images) instead, if you want to use conda via docker.

**Comment by wvxvw** [comment]
They all have the same problem.

To be more specific, none of the conda images can be used right now in Jenkins with Kubernetes plugin to create containers in Jenkin agent's pods because of how the images themselves are built.

Docker guidelines for creating containers suggest using `--` to separate options and arguments to `run` from the options and arguments to the entripoint, and that's how Jenkins plugin is using them.

**Comment by wvxvw** [comment]
Actually, nevermind. I misinterpreted the error. The problem was with the user's id, which Jenkins' Kubernetes plugin isn't flexible around: it wants UID and GID to be 1000, but the one in the image was 1001.
