### ISSUE TITLE
Changing the Locale, Region, and Language to be Different than Machine's Region, Locale, Language Settings

### ISSUE THREAD

**Issue by joeld1** [ContinuumIO/docker-images#235]
Is it possible to run the following docker image

```
docker run -i -t -p 8888:8888 continuumio/anaconda3 /bin/bash -c "/opt/conda/bin/conda install jupyter -y --quiet && mkdir /opt/notebooks && /opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip='*' --port=8888 --no-browser"
```

in a different region and locale such that every shell command and conda command is in that foreign language? I'm located in the US so currently all of my tools and language settings are in English.

I'm interested in emulating the locale and region (and dev-environment) of end-users for some mini tutorials on using docker and creating Jupyter notebooks.

Some languages I'm interested in:

- Italian (Italy)
- French (Switzerland and France)
- German (Germany)
- Spanish (Mexico, Spain)
- Portuguese (Brazilian, Portugal)
- Chinese (Mandarin, China)
- English (US; so end users can use English instead of their local language)

Is there anyway to override the command such that it changes my region and language to match that of the end users'? 

Thank you for all the work on these images by the way; they are very useful!

**Comment by dbast** [comment]
This does not have much to do with the Docker Container, it is more a question of how to setup locales on Linux systems.

You can set the variables like LANG, LANGUAGE, LC_ALL to e.g. it_IT.UTF-8 for Italian.

This tells you what locales are available: `locale -a`. Via `locale-gen fr_FR.UTF-8` more locales can be generated.

Full command would be e.g.:
`docker run -i -t -p 8888:8888 continuumio/anaconda3 /bin/bash -c "/opt/conda/bin/conda install jupyter -y --quiet && mkdir /opt/notebooks && LC_ALL=it_IT.UTF-8 /opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip='*' --port=8888 --no-browser"`

If jupyter supports different locales is a different question.
