### ISSUE TITLE
miniconda3:4.10.3-alpine is not alpine

### ISSUE THREAD

**Issue by MatanAmoyal** [ContinuumIO/docker-images#239]
Hey

looks like continuumio/miniconda3:4.10.3-alpine is not alpine

docker run -it --rm continuumio/miniconda3:4.10.3-alpine
(base) root@7719d1bcb0ec:/# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by justinGilmer** [comment]
Can confirm, ran into similar issue today. Discovered  that `which apk` did not work, nor was `apk` in `/sbin`

**Comment by dbast** [comment]
Very strange. Here the links to
* the Alpine Dockerfile: https://github.com/ContinuumIO/docker-images/blob/master/miniconda3/alpine/Dockerfile
* the Alpine build+publish action file: https://github.com/ContinuumIO/docker-images/blob/master/.github/workflows/miniconda_alpine_ci.yml
* The build and publish log for the 4.10.3 tagged build: https://github.com/ContinuumIO/docker-images/runs/3143450466?check_suite_focus=true

This show a real alpine:
* `docker run -it --rm continuumio/miniconda3:4.10.3-alpine@sha256:653b00c617c41fecafc52e226767e8ab8251c2fd0f3100eee60135273fdbb324 cat /etc/os-release`
* `docker run -it --rm continuumio/miniconda3:master-alpine cat /etc/os-release`

But why does `docker run -it --rm continuumio/miniconda3:4.10.3-alpine cat /etc/os-release` not work? Did anything overwrite it? Not other action should publish with an alpine suffix.

**Comment by dbast** [comment]
This should be fixed now:

```
docker run -it --rm continuumio/miniconda3:4.10.3-alpine cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.14.0
PRETTY_NAME="Alpine Linux v3.14"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```
