### ISSUE TITLE
Recent docker images seem to all base off of Alphine

### ISSUE THREAD

**Issue by SHuang-Broad** [ContinuumIO/docker-images#242]
I need to use some package that isn't supported on Alpine, so just tried to pulling the version that should be based off of Debian

```bash
docker pull continuumio/miniconda3:master
# then create a container, got the following
docker run -it 462f45032b06
cat /proc/version
Linux version 5.10.47-linuxkit (root@buildkitsandbox) (gcc (Alpine 10.2.1_pre1) 10.2.1 20201203, GNU ld (GNU Binutils) 2.35.2) #1 SMP Sat Jul 3 21:51:47 UTC 2021
```

similarly, but pulling Alpine specifically:

```bash
docker pull continuumio/miniconda3:master-alpine
docker run -it 77ffadcad7dd
Linux version 5.10.47-linuxkit (root@buildkitsandbox) (gcc (Alpine 10.2.1_pre1) 10.2.1 20201203, GNU ld (GNU Binutils) 2.35.2) #1 SMP Sat Jul 3 21:51:47 UTC 2021
```
Exact same information.

Am I misunderstanding something?

Thanks!

**Comment by dbast** [comment]
Not reproducible, thus closing. Please reopen if the issue persists.

**Comment by SHuang-Broad** [comment]
I apologize. It was due to me not understanding how to get the OS information.
Thank you for confirming!

Steve
