### ISSUE TITLE
Use HTTPS when fetching Miniconda

### ISSUE THREAD

**Issue by rgbkrk** [ContinuumIO/docker-images#3]
When the miniconda installer is grabbed, it's done over HTTP. Perhaps as an upstream issue, repo.continuum.io should have certificates.

**Comment by tswicegood** [comment]
@rgbkrk -- thanks for the suggestion.

@tpowellcio -- looks like `repo.continuum.io` isn't available over HTTPS.  Is this something you can take care of?

**Comment by tswicegood** [comment]
@tpowellcio you can assign back to me to make the adjustments on the Docker image once the server responds to HTTPS.

**Comment by tpowellcio** [comment]
@tswicegood -- I think we are out of luck for SSL on our repo.continuum.io
http://stackoverflow.com/questions/11201316/how-to-configure-ssl-for-amazon-s3-bucket

**Comment by tswicegood** [comment]
@tpowellcio any chance of putting repo.continuum.io on CloudFlare?  Another option might be using binstar.org.  @srossross any thoughts on using binstar.org to host Miniconda installers?

**Comment by tpowellcio** [comment]
@tswicegood We are looking into moving some of our cloud service next month after the office move. @lilmatt and myself will add this to the list of considerations.

**Comment by srossross** [comment]
Yes, this would be pretty easy using the `file` package type:

You can upload arbitrary files like this:

```sh
binstar upload INSTALLER.sh  \
               --user <USER> \
               --package <INSTALLER NAME> \
               --version <VERSION> \
               -t file
```

Here is an example of what a download page looks like for a README.md file I uploaded using this command: https://downloads.binstar.org/sean/random_readme

```sh
binstar upload README.md  \
               --user sean \
               --package random_readme \
               --version 1.1 \
               -t file
```

Also, if there is a way to auto-detect the type version inf, etc. the `--version` and the `-t` file options would be redundant.

**Comment by tswicegood** [comment]
@ilanschnell @teoliphant thoughts?  I'm sure it'd make @lilmatt happy because its one less thing on hardware behind the firewall. :-)

**Comment by mutirri** [comment]
Keep also in mind that some of our internal tools (`analog` or `amictl` for example but it may be more) depends on current location of anaconda/miniconda installers (fetches from repo.continuum.io/*, path regexps, etc.).
