### ISSUE TITLE
miniconda3 on alpine linux

### ISSUE THREAD

**Issue by Maxyme** [ContinuumIO/docker-images#30]
Would it be possible to add a version of the dockerfile using alpine linux instead of full debian? This would make it much faster to download and upload.

See example for redis on alpine:
https://github.com/docker-library/redis/blob/6cb8a8015f126e2a7251c5d011b86b657e9febd6/3.2/alpine/Dockerfile

**Comment by jontonsoup** [comment]
@Maxyme Not maintainer, but FYI. I've tried building on both alpine and debian... the size difference is pretty minimal.

**Comment by andreacassioli** [comment]
@jontonsoup Could you share the Dockerfile?

**Comment by andreacassioli** [comment]
Just to mention, from docker image ls

* python3 alpine :  92MB
* continuumio/miniconda3: 571MB

Either miniconda is not that minimal, or alpine is much smaller, or both!

**Comment by jontonsoup** [comment]
@andreacassioli i threw it out after the test, but your comparison above is not accurate. python 3 alpine doesn't include all the dependencies miniconda includes. Its not a fair comparison. In my experience, its all the libraries that take up the space.

**Comment by mingwandroid** [comment]
Also `continuumio/miniconda3: 571MB` is wrong, we use hardlinks, I suspect you are counting them twice.

**Comment by mingwandroid** [comment]
Oh and we also keep the tarballs present for all packages, these can be cleaned via conda if you are attempting to reduce a docker image size. Miniconda is comprised of about 33 packages.

**Comment by andreacassioli** [comment]
@mingwandroid Thanks for the suggestion! It would be nice if Continuum could provide a microconda image. I mean, of course one could go an tweak it, but if you could work out a very minimal image would be great.

**Comment by msarahan** [comment]
We do, actually: https://hub.docker.com/r/continuumio/miniconda/

**Comment by mrocklin** [comment]
See also https://github.com/ContinuumIO/docker-images/pull/77, which shaves of 70MB or so

**Comment by mrocklin** [comment]
> Either miniconda is not that minimal, or alpine is much smaller, or both!

Miniconda is not that minimal.  It outweighs the entire debian image by several times.  I don't think that debian vs alpine is yes the limiting factor.

**Comment by OrangeDog** [comment]
This has been done.
continuumio/miniconda3:4.7.12 is 151MB
continuumio/miniconda3:4.7.12-alpine is 55MB

**Comment by mrocklin** [comment]
Nice.

**Comment by andreacassioli** [comment]
awesome
