### ISSUE TITLE
Messed up (no) fonts in Qt apps - missing fontconfig?

### ISSUE THREAD

**Issue by hainesr** [ContinuumIO/docker-images#31]
I have a script that I am running (I didn't write it myself) that uses python and Qt, via matplotlib, to generate a GUI. When running it using the anaconda docker image I don't see any text in the menus, etc - just a load of black squares.

If I install fontconfig (`apt-get install fontconfig`) into the running container then everything then starts working perfectly.

Does fontconfig need to be added to the image build? Or is there some other config missing that would solve the problem another way?

Thanks!
Rob

**Comment by hainesr** [comment]
PS. Happy to submit a PR if it helps!

**Comment by bollwyvl** [comment]
@hainesr there is a conda-forge fontconfig:
```
conda install -c conda-forge fontconfig
```
Might be an immediate fix... but there are number of secret dependencies like this that have bitten me in the past as well!

**Comment by hainesr** [comment]
@bollwyvl thanks. I'm not sure to what extent it's best to use the OS package or a conda package for this.

Happy for someone with more knowledge than me to comment.

**Comment by dbast** [comment]
This should be solved since long. Nowadays qt in defaults and conda-forge depend on fontconfig (fontconfig in conda-forge also brings fonts by depending on fonts-conda-ecosystem). Thus closing, please reopen, if this still is an issue.
