### ISSUE TITLE
Python 3.7 with continuumio/miniconda3

### ISSUE THREAD

**Issue by jamesbraza** [ContinuumIO/docker-images#320]
Running the following command, I can see the Python version is `3.9.12`:

```bash
docker run -it continuumio/miniconda3 python --version
```

Is it possible to somehow go with Python 3.7?

**Comment by gregdan3** [comment]
Once you create a conda environment, it will have either the latest python version that is possible for your project or one you specify.

For example:

```bash
conda create -n project -c conda-forge ... python=3.7.10
```

Why do you need conda itself to run with a different Python version?

**Comment by jamesbraza** [comment]
This is a good point, thank you!  That does provide a solution.

I was sort of wondering if somehow there were tags published for different Python versions, but since opening this I have realized there are not.  So I am going to close this out.
