### ISSUE TITLE
Add tag as a label to image

### ISSUE THREAD

**Issue by jamesbraza** [ContinuumIO/docker-images#325]
I wanted to figure out the tag associated with `continuumio/miniconda3:latest`.

I pulled up [Find Version Tag for Latest Docker Image](https://ryandaniels.ca/blog/find-version-tag-latest-docker-image/) and tried trick #1: 

```bash
> docker images
REPOSITORY                     TAG             IMAGE ID       CREATED         SIZE
continuumio/miniconda3         latest          ce7d119281a1   4 months ago    403MB
> IMAGE_ID=ce7d119281a1
> docker image inspect --format '{{json .}}' "$IMAGE_ID" | jq -r '. | {Id: .Id, Digest: .Digest, RepoDigests: .RepoDigests, Labels: .Config.Labels}'

{
  "Id": "sha256:ce7d119281a1f4685ce6ca66b355c88baa44522ac6a54aee86be96d14ab6dfda",
  "Digest": null,
  "RepoDigests": [
    "continuumio/miniconda3@sha256:977263e8d1e476972fddab1c75fe050dd3cd17626390e874448bd92721fd659b"
  ],
  "Labels": {
    "maintainer": "Anaconda, Inc"
  }
}
```

I think it could be cool if the tag showed up as a label!  Alternately, how would you associate `latest` with a tag?

I ended up using trick #2 just `docker pull`ing images until I found a match in `4.12.0`.

**Comment by dbast** [comment]
Done via https://github.com/ContinuumIO/docker-images/pull/311 ... to be released soon.
