### ISSUE TITLE
[conda_builder_linux ] Cannot use start_cpp98.sh with script

### ISSUE THREAD

**Issue by bjodah** [ContinuumIO/docker-images#33]
This used to work:

```
$ start_cpp98.sh my_build_script.sh
```

it doesn't any longer, I'm pretty sure this is to blame:
https://github.com/ContinuumIO/docker-images/blame/master/conda_builder_linux/docker_wrapper.sh#L32

any thoughts @stefanseefeld?

**Comment by msarahan** [comment]
It should work, but you need to put - -  in between any docker args(you have none)  and command args. 

```
$ start_cpp98.sh - -  my_build_script.sh
```

**Comment by bjodah** [comment]
I see, yes that worked. (I think the README still describes the older version of docker_wrapper.sh)
Thanks!

Perhaps an example like this would be instructive in the `README`?
```
$ cat <<EOF >my_test.sh
g++ --version
EOF
$ start_cpp98.sh -v $(pwd):/home/dev/current_folder -- ./current_folder/my_test.sh
g++ (GCC) 5.2.0
...
```

**Comment by msarahan** [comment]
Thanks. I will update the readme. Not closing this issue until I have done so.

**Comment by dbast** [comment]
The mentioned script does not exist anymore and there are the compiler action scripts nowadays, thus closing. Please reopen, if this still is an issue.
