### ISSUE TITLE
QUESTION - docker-miniconda with Jupyter - assign volume

### ISSUE THREAD

**Issue by ddjustina** [ContinuumIO/docker-images#331]
I would like to interact with the miniconda container but I don't know how to assign a volume.

I would like customize the code block bellow from the [miniconda docker page](https://hub.docker.com/r/continuumio/miniconda3).
```shell
docker run -i -t -p 8888:8888  continuumio/miniconda3 /bin/bash -c "\
    conda install jupyter -y --quiet && \
    mkdir -p /opt/notebooks && \
    jupyter notebook \
    --notebook-dir=/opt/notebooks --ip='*' --port=8888 \
    --no-browser --allow-root"
```

I would like to assign a local volume (code bellow), but I'm not sure to o insert it in the code block above
```shell
-v C:\Users\name\docker_volume:/opt
```

**Comment by dbast** [comment]
This is not a user support forum, but this should work
```shell
docker run -i -t -p 8888:8888  -v C:\Users\name\docker_volume:/mnt continuumio/miniconda3 /bin/bash -c "\
    conda install jupyter -y --quiet && \
    mkdir -p /opt/notebooks && \
    jupyter notebook \
    --notebook-dir=/opt/notebooks --ip='*' --port=8888 \
    --no-browser --allow-root"
```

don't mount to `/opt` as miniconda is installed to `/opt/conda`.
