### ISSUE TITLE
binutils too young

### ISSUE THREAD

**Issue by pitrou** [ContinuumIO/docker-images#37]
The binutils version on the image is too young: libraries built with it can be incompatible with older binutils due to the introduction of a new "relocation" kind.

See example at:
https://travis-ci.org/numba/llvmlite/jobs/147789631#L373

See similar issues at: https://bugs.launchpad.net/ubuntu/+source/binutils/+bug/1545653 and https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=808205

**Comment by pitrou** [comment]
Sorry, the Travis-CI log was clobbered by a new build. The error was the same as in the issues above: `unrecognized relocation (0x2a)`.

**Comment by dbast** [comment]
Thanks for reporting. Closing as this is now 5 years old and a bit stale. Images got updated since then. Please reopen, if the issue is still there.
