### ISSUE TITLE
What's the best way of building own docker image using a particular Python version?

### ISSUE THREAD

**Issue by rs2** [ContinuumIO/docker-images#40]
Instead of using e.g. https://repo.continuum.io/archive/Anaconda3-4.1.1-Linux-x86_64.sh?

**Comment by dbast** [comment]
Instead create a new environment via e.g. `conda create --name myenv python==3.X && conda activate myenv && python --version`

This way a new environment with different Python version and other packages is created, which is independent from the base environment.
