### ISSUE TITLE
packge lsb-release required

### ISSUE THREAD

**Issue by tiagoantao** [ContinuumIO/docker-images#42]
Package lsb-release is required so that `conda install gcc` works.
This is quite explanatory, just test with the command above and it will return an error.

**Comment by basnijholt** [comment]
I am encountering the same error.

**Comment by dbast** [comment]
Thanks for reporting. The equivalent command nowadays is `docker run -i -t continuumio/miniconda3:4.10.3 conda install gcc_linux-64=7` ... and that works fine, thus closing. Please reopen if this still is an issue.
