### ISSUE TITLE
What's the purpose of tini in the Dockerfiles?

### ISSUE THREAD

**Issue by connercowling** [ContinuumIO/docker-images#43]
I'm going out on a limb here and hoping someone will be kind enough to satisfy my curiosity.  Thanks in advance :)

**Comment by koverholt** [comment]
Thanks for your interest/curiosity! `tini` serves as (one of) the recommended ways to use a simple init system as the entrypoint. See #18 for more information.

**Comment by connercowling** [comment]
Ahh yeah [this](https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/) is what I was looking for.  Very interesting.  Thanks much.
