### ISSUE TITLE
Creating the anaconda3/Dockerfile fails

### ISSUE THREAD

**Issue by yaron-idan** [ContinuumIO/docker-images#46]
When trying to build the anaconda3 image locally I get the following error - 
```
E: Failed to fetch http://httpredir.debian.org/debian/pool/main/s/shared-mime-info/shared-mime-info_1.3-1_amd64.deb  Error reading from server. Remote end closed connection ¡IP: 5.153.231.35 80¿

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

After adding the --fix-missing flag to the apt-get install command the image builds fine. Shouldn't that be added to the dockerfile?

**Comment by dbast** [comment]
This should be not an issue anymore. All images currently are test-built via Github actions on any change to proof that they build fine. Thus closing, please reopen, if that still is an issue.
