### ISSUE TITLE
Anaconda images aren't available on Docker Hub

### ISSUE THREAD

**Issue by kwbeam** [ContinuumIO/docker-images#5]
The GitHub READMEs say they can be pulled:

https://github.com/ContinuumIO/docker-images/blob/master/anaconda/README.md
https://github.com/ContinuumIO/docker-images/blob/master/anaconda3/README.md

But they don't seem to be available yet:

https://registry.hub.docker.com/search?q=continuumio

    $ docker pull continuumio/anaconda
    Pulling repository continuumio/anaconda
    FATA[0002] Tag latest not found in repository continuumio/anaconda

(same with anaconda3)

**Comment by mutirri** [comment]
Now it should be fine: https://registry.hub.docker.com/repos/continuumio/
```
$ docker search continuumio
NAME                         DESCRIPTION          STARS     OFFICIAL   AUTOMATED
continuumio/miniconda                             7                    [OK]
continuumio/memex_explorer   memex explorer app   1                    
continuumio/anaconda                              0                    [OK]
continuumio/anaconda3                             0                    [OK]
continuumio/miniconda3                            0                    [OK]

$ docker pull continuumio/anaconda
$ docker run -i -t continuumio/anaconda /bin/bash
root@71043ad13405:/# which conda
/opt/conda/bin/conda
root@71043ad13405:/# 
```
