### ISSUE TITLE
anaconda3 README has wrong version of Python 

### ISSUE THREAD

**Issue by anandology** [ContinuumIO/docker-images#55]
The README says the container has *Anaconda (based on Python 3.5)*, but it actually has *Anaconda 4.3.1 based on Python 3.6*.

**Comment by dbast** [comment]
This got fixed by https://github.com/ContinuumIO/docker-images/pull/236 . Please also look into the Dockerfiles to see what was exactly installed. Thus closing, please reopen, if this still is an issue.
