### ISSUE TITLE
trouble  using a program installed by Miniconda

### ISSUE THREAD

**Issue by momo12321** [ContinuumIO/docker-images#60]
I have a program that's called MAC2 and it's requiring HTSeq as a prerequisite .
 I managed to install all the prerequisites using miniconda.  HTSeq couldn't be detected by conda, so I used pip of the miniconda to install it(it installed in miniconda2/bin) 

However whenever I try to run the program i get this message:
/home/pk2/miniconda2/lib/python2.7/site-packages/HTSeq/_HTSeq.so: undefined symbol: PyFPE_jbuf. This module is required.

I read online , they said it's probably because another HTSeq is installed somewhere else but : 
I removed all the other HTSeq install using sudo pip uninstall HTSeq
Also my path is directed immediately to the miniconda work environment .

Any insight would helpful.

**Comment by dbast** [comment]
Seems like the pip installed package is missing symbols. Mixing pip and conda packages does not always work well. htseq can now be install from bioconda, maybe that helps `conda create --name myenv bioconda::htseq`. Closing as stale, please reopen, if the issue is still there.
