### ISSUE TITLE
continuumio/anaconda docker image Kernel Dies

### ISSUE THREAD

**Issue by pgensler** [ContinuumIO/docker-images#61]
Not sure why this keeps happenning to me, but my kernel keeps dieing on my Docker image from continuumio/anaconda. I try running the container with the following command:
`docker run -i -t -p 8888:8888 continuumio/anaconda /bin/bash -c "/opt/conda/bin/conda install jupyter -y --quiet && mkdir /opt/notebooks && /opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip='*' --port=8888 --no-browser"`
 and I end up with "an unexpected error has occurred", which I would presume relates to this:
https://github.com/conda/conda/issues/3935

Should I try to re-install anaconda/update conda on my local machine before trying to use the container? Is the container using my local kernel of Python? Any help would be appreciated.

**Comment by dbast** [comment]
The old anaconda Python 2 based image is EOL. Tried to reproduce this with the newer anaconda3 Python3 based image and the does work with out error. From the anaconda3/README.md:
```
docker run -i -t -p 8888:8888 continuumio/anaconda3 /bin/bash -c "\
        conda install jupyter -y --quiet && \
        mkdir -p /opt/notebooks && \
        jupyter notebook \
        --notebook-dir=/opt/notebooks --ip='*' --port=8888 \
        --no-browser --allow-root"
```

Thus closing. Please reopen, if that still is an issue.
