### ISSUE TITLE
Can't install anything with gcc and pip in Miniconda 4.3.27

### ISSUE THREAD

**Issue by devinXL8** [ContinuumIO/docker-images#67]
`    unable to execute 'x86_64-conda_cos6-linux-gnu-gcc': No such file or directory
    error: command 'x86_64-conda_cos6-linux-gnu-gcc' failed with exit status 1`

**Comment by msarahan** [comment]
Duplicate of https://github.com/conda/conda/issues/6030 - please see that issue.
