### ISSUE TITLE
Please upgrade the Dockerfile to resolve build failures due to a bad conda release

### ISSUE THREAD

**Issue by gorbachev** [ContinuumIO/docker-images#68]
Building Docker images based on the continuumio/anaconda3 image fail with:

unable to execute 'x86_64-conda_cos6-linux-gnu-gcc': No such file or directory
error: command 'x86_64-conda_cos6-linux-gnu-gcc' failed with exit status 1

This happens, for example when building menpo python module to include in the Docker image.

From what I can gather this is an issue with the 9/27 conda build having a bug. This has since been fixed and a new release is out on 10/2, if I followed the discussions on this correctly. However, the Dockerfile in this project hasn't been updated to include this new release.

I believe the 5.0.0.1 releases at https://repo.continuum.io/archive/ would fix this?

**Comment by dbast** [comment]
This should be fixed by newer anaconda3 releases, as mentioned. Thus closing, please reopen, if that still is an issue.
