### ISSUE TITLE
Can't build your docker files

### ISSUE THREAD

**Issue by geostant** [ContinuumIO/docker-images#74]
I'm trying to build your dockerfiles (both miniconda and conda) where I've only edited the conda version from 64bit to 32bit - unfortunately in any case (even with 64bit) I always get the same error:

> /root/anaconda.sh: line 358: /opt/conda/pkgs/python-2.7.14-h41cc02d_21/bin/python: No such file or directory

The above error happens on step 5/9 (anaconda installation)

I would appreciate help here as I need specifically 32bit, otherwise I would have pulled a pre-built image from docker hub.

Thanks

**Comment by dbast** [comment]
Thanks for reporting. This got a bit stale, meanwhile linux-32 is not supported anymore. Thus closing.
