### ISSUE TITLE
latest images broken due to Docker-related issue in conda 4.4.10

### ISSUE THREAD

**Issue by mbargull** [ContinuumIO/docker-images#79]
https://github.com/ContinuumIO/docker-images/pull/78 updated `continuumio/miniconda3:latest` to use `conda 4.4.10`, but this is problematic due to https://github.com/conda/conda/issues/6811#issuecomment-364894274.
Could we get a non-`conda >4.4.7,<4.4.11` image with `continuumio/miniconda3:latest`?

**Comment by dbast** [comment]
This should be fixed since long by newer releases. Thus closing, please reopen, if this still is an issue.
