### ISSUE TITLE
Cannot import matplotlib.pyplot in docker container

### ISSUE THREAD

**Issue by mhearne-usgs** [ContinuumIO/docker-images#8]
I get this error: ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory

The full error output is below.

I am running Docker using boot2docker on a Mac.

bash-3.2$ docker run -i -t continuumio/anaconda /bin/bash
root@a14804e988fd:/# ipython
WARNING: Readline services not available or not loaded.
WARNING: The auto-indent feature requires the readline library
Python 2.7.9 |Anaconda 2.2.0 (64-bit)| (default, Mar  9 2015, 16:20:48) 
Type "copyright", "credits" or "license" for more information.

IPython 3.0.0 -- An enhanced Interactive Python.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import matplotlib.pyplot
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-6f467123fe04> in <module>()
----> 1 import matplotlib.pyplot

/opt/conda/lib/python2.7/site-packages/matplotlib/pyplot.py in <module>()
    107 
    108 from matplotlib.backends import pylab_setup
--> 109 _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
    110 
    111 

/opt/conda/lib/python2.7/site-packages/matplotlib/backends/__init__.pyc in pylab_setup()
     30     # imports. 0 means only perform absolute imports.
     31     backend_mod = __import__(backend_name,
---> 32                              globals(),locals(),[backend_name],0)
     33 
     34     # Things we pull in from all backends

/opt/conda/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py in <module>()
     15 from matplotlib.figure import Figure
     16 
---> 17 from .backend_qt5agg import NavigationToolbar2QTAgg
     18 from .backend_qt5agg import FigureCanvasQTAggBase
     19 

/opt/conda/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py in <module>()
     16 
     17 from .backend_agg import FigureCanvasAgg
---> 18 from .backend_qt5 import QtCore
     19 from .backend_qt5 import QtGui
     20 from .backend_qt5 import FigureManagerQT

/opt/conda/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py in <module>()
     29     figureoptions = None
     30 
---> 31 from .qt_compat import QtCore, QtGui, QtWidgets, _getSaveFileName, __version__
     32 from matplotlib.backends.qt_editor.formsubplottool import UiSubplotTool
     33 

/opt/conda/lib/python2.7/site-packages/matplotlib/backends/qt_compat.py in <module>()
     89     if QT_API in [QT_API_PYQT, QT_API_PYQTv2]:  # PyQt4 API
     90 
---> 91         from PyQt4 import QtCore, QtGui
     92 
     93         try:

ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory

**Comment by bnlawrence** [comment]
(Me too, same issue)

**Comment by mhearne-usgs** [comment]
@bnlawrence Are you on OSX?  Because I just tried your solution and realized that I have no Internet connectivity from inside my container.  I'm assuming that's an issue outside Anaconda's domain...

**Comment by bnlawrence** [comment]
(Yes, I was on OSX, I can't recall if I did anything magic to have internet connectivity from inside the container.)

**Comment by jakirkham** [comment]
Saw the same issue, but with PyQt4, which seems to be where this error stems from in your Matplotlib import.

**Comment by mutirri** [comment]
New images (with installed missing libarries) are available here: https://registry.hub.docker.com/repos/continuumio/

**Comment by kitianFresh** [comment]
yes, i got the same error when i using docker, and i install anacoda in docker container, then i got 
ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory, below is my error messages:

root@bc4b7e942a56:/home/study/ocr3/code# python server1.py 
/root/anaconda3/lib/python3.5/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
/root/anaconda3/lib/python3.5/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "server1.py", line 5, in <module>
    from ocr import OCRNeuralNetwork
  File "/home/study/ocr3/code/ocr.py", line 2, in <module>
    import matplotlib.pyplot as plt
  File "/root/anaconda3/lib/python3.5/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/root/anaconda3/lib/python3.5/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/root/anaconda3/lib/python3.5/site-packages/matplotlib/backends/backend_qt4agg.py", line 18, in <module>
    from .backend_qt5agg import FigureCanvasQTAggBase as _FigureCanvasQTAggBase
  File "/root/anaconda3/lib/python3.5/site-packages/matplotlib/backends/backend_qt5agg.py", line 15, in <module>
    from .backend_qt5 import QtCore
  File "/root/anaconda3/lib/python3.5/site-packages/matplotlib/backends/backend_qt5.py", line 31, in <module>
    from .qt_compat import QtCore, QtGui, QtWidgets, _getSaveFileName, __version__
  File "/root/anaconda3/lib/python3.5/site-packages/matplotlib/backends/qt_compat.py", line 124, in <module>
    from PyQt4 import QtCore, QtGui
ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory

**Comment by mutirri** [comment]
Hi,

What version of image is being used?
I tested latest (`4.2.0`) `Anaconda` and `Anaconda3` images with the quite simple code:
```python
import matplotlib
import matplotlib.pyplot as plt
matplotlib.get_backend()
plt.plot([1,2,3,4])
plt.ylabel('numbers')
plt.show()
```

1. Both images have installed pyqt5 package (in `5.6.0` version) as default.
  However matplotlib backends still wants to use `PyQt4`.

  ```
...
/opt/conda/lib/python2.7/site-packages/matplotlib/backends/qt_compat.py in <module>()
    135     # have been changed in the above if block
    136     if QT_API in [QT_API_PYQT, QT_API_PYQTv2]:  # PyQt4 API
--> 137         from PyQt4 import QtCore, QtGui
    138 
    139         try:

ImportError: No module named PyQt4
  ```
  This is somehow related to bug (especially the part related to mixing backends):
  https://github.com/matplotlib/matplotlib/issues/6420#issuecomment-219224543

2. To overcome above problem I checked a lot of packages.
  Finally I got the problematic one: `libgl1-mesa-glx`
  So, after performing:
  ```bash
  $ apt-get -y install libgl1-mesa-glx
  ```
  I'm able to get `Qt5Agg` backend as default and of course properly rendered plot.
  ![plot](https://cloud.githubusercontent.com/assets/1040331/19888963/5facbd80-a032-11e6-83d8-0859c7bb8ba9.png)

Best.
