### ISSUE TITLE
make is not included in anaconda3 docker image

### ISSUE THREAD

**Issue by jennirinker** [ContinuumIO/docker-images#84]
I pulled the latest anaconda3 docker image today, and when I tried to use sphinx to build my docs it threw `bash: make: command not found`. Is there a reason for not including `make` in the anaconda3 docker image?

In case anyone else needs it, here is the workaround I'm using: either `apt-get install make` from within an image or add `RUN apt-get install make` to the dockerfile you use to build your own image.

**Comment by soapy1** [comment]
We don't include make since anaconda does not depend on it. If you would like to run sphinx inside a docker container I would suggest building a dockerfile for your specific purpose
