### ISSUE TITLE
miniconda3 Dockerfile - package installs (libxext6 libsm6 libxrender1 ...)

### ISSUE THREAD

**Issue by mmontana** [ContinuumIO/docker-images#99]
Is there a specific reason that in the **miniconda Dockerfile** we have

```shell
RUN apt-get update --fix-missing && apt-get install -y wget bzip2 ca-certificates \
    libglib2.0-0 libxext6 libsm6 libxrender1 \
    git mercurial subversion
```

while in the **miniconda3 Dockerfile** these statements are missing? 
I stumbled upon this when I encountered a bug running some matplotlib tests in CI in a miniconda3 container, the missing 
`libxext6 libsm6 libxrender1`
caused the following bug:
https://github.com/conda/conda/issues/1051

Of course, manually installing the packages solve the problem and the solution is clear. I was just wondering if there is a certain reason for not installing these packages in the Dockerfile. Especially because this bug is not encountered when using the miniconda or anaconda/anaconda3 images.

**Comment by mingwandroid** [comment]
Because Miniconda doesn't need them clearly.

**Comment by mingwandroid** [comment]
Miniconda included only the essentials for python. If you install something
else later that links to system libraries then it's up to you to install
those too.

**Comment by mmontana** [comment]
Sure. Maybe my question was a bit unclear: why then install the libraries in the miniconda image but not in the miniconda3 image? This was the actual thing that seemed weird to me.

**Comment by mingwandroid** [comment]
Because IMHO they were added incorrectly?
